name = "final_project"
defaultTargets = ["final_project"]

[leanOptions]
autoImplicit = false
linter.unusedVariables = false 

[moreServerOptions]
linter.unusedTactic = false
linter.unreachableTactic = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "a719ba5c3115d47b68bf0497a9dd1bcbb21ea663"

[[require]]
name = "mdgen"
git = "https://github.com/Seasawher/mdgen"
rev = "bdfc2e355fbd5003be7094b3c99ff9d833aff7da"
